name: br_api
description: >-
  Package com base na Brasil API. Classes/modelos para uso de suas funcionalidades. 
  Por favor, leia os termos de uso da API.
version: 1.0.1
documentation: https://github.com/PedroHAVeloso/br_api_dart/blob/main/DOCS.md
repository: https://github.com/PedroHAVeloso/br_api_dart
homepage: https://github.com/PedroHAVeloso/br_api_dart

environment:
  sdk: ^3.0.6

dependencies:
  http: ^1.1.0

dev_dependencies:
  dartdoc: ^6.3.0
  lints: ^2.1.1
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1
